name: Build and Publish Image to Docker Hub
on:
    [workflow_dispatch]

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v4

          - name: Build image
            run: docker build ./ -t potenselit/er-app-ui:latest

          - name: Push image to Docker Hub
            run: |
              docker login -u potenselit -p ${{ secrets.DOCKER_HUB_TOKEN }}
              docker push potenselit/er-app-ui:latest